apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: stress-cpu
  namespace: chaos-mesh
spec:
  mode: all
  selector:
    labelSelectors:
      app: kafka
    namespaces:
    - kafka
  stressors:
    cpu: 
      workers: 5
      load: 100
  duration: "30s"
  scheduler:
    cron: "@every 1m"